#!/usr/bin/env bash
#
set -e

cd "$(dirname "$0")/.."

log() {
  echo -e "\\e[32m==> $*...\\e[0m"
}

log2() {
  echo -e "\\e[32m====> $*...\\e[0m"
}

ok() {
  echo -e "    \\e[1mOK\\e[0m"
}

fail() {
  echo -e "\\e[1m\\e[41m!!! $*\\e[0m"
  exit 1
}

mkdir -p build/{linux,darwin}

if [[ -z $1 || $1 == 'darwin' ]]; then
  mkdir -p build/darwin
  log "Building (slow_log_parse) for darwin"
  GOOS=darwin go build -o build/darwin/slow_log_parse cmd/main.go || fail
  ok
fi;

if [[ -z $1 || $1 == 'linux' ]]; then
  mkdir -p build/linux
  log "Building (slow_log_parse) for linux"
  GOOS=linux go build -o build/linux/slow_log_parse cmd/main.go || fail
  ok
fi;
